### ISSUE TITLE
index.js:61 exitWithError when attempting to `yo famous-triggerio`

### ISSUE THREAD

**Issue by tconroy** [trigger-corp/generator-famous-triggerio#1]
I cannot use the generator, when I attempt to run `yo famous-triggerio` in a directory, I am greeted with the following errors:

```
/usr/local/lib/node_modules/generator-famous-triggerio/app/index.js:61
                        this._exitWithError(error);
                             ^
TypeError: Object #<ChildProcess> has no method '_exitWithError'
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/generator-famous-triggerio/app/index.js:61:30)
    at ChildProcess.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:808:12)
```

steps to reproduce:
1. install dependencies - `npm install -g grunt-cli yo bower generator-famous-triggerio`
2. make a test directory and enter it - `mkdir test && cd test`
3. run generator - `yo famous-triggerio`
4. above error occurs.

**Comment by antoinevg** [comment]
It shouldn't be giving that specific error but my guess is that yo can't find the "forge" binary on your system path.

I've comitted an update to the generator that should give a more helpful error message: c4d2da8b5a45e2a940c6411a6be53d47fd906c6b

Can you do a "npm update generator-famous-triggerio" and try again?

**Comment by tconroy** [comment]
the error being thrown is now: 

`We are experiencing a dastardly error event: Error: spawn ENOENT`

**Comment by antoinevg** [comment]
What do you get if you type `which forge` on the command line?

If it doesn't output a directory location then you'll need to add the forge tools directory to your system path by adding something like this to your `~/.profile` or `~/.bashrc` files:

```
export PATH=$PATH:~/Library/Trigger\ Toolkit
```

If you're not on OSX it should be the directory you installed the Toolkit into.

**Comment by tconroy** [comment]
`forge is aliased to /Users/Tom/Library/'Trigger Toolkit'/forge`

I can enter Forge commands fine, but as soon as I run `yo famous-triggerio` it dies.

**Comment by tconroy** [comment]
Just reinstalled npm, node, bower, grunt, grunt-cli, gulp and yo. 

versions:
- npm: 1.4.28
- node: 0.10.33
- bower: 1.3.12
- grunt: 0.1.13
- yo: 1.3.3 

ran: 
    $ npm install -g generator-famous-triggerio
    $ yo famous-triggerio
    ? Would you mind telling me your username on GitHub? tconroy
    We are experiencing a dastardly error event: Error: spawn ENOENT
    $

Any guesses? This is on OSX 10.9.5 (Mavericks).

**Comment by michaelbina** [comment]
I'm having this same problem.  Did you ever get around it?

**Comment by tconroy** [comment]
No, I was unable to resolve the issue. Ultimately ended up going with an alternative to Trigger with better famous integration.

**Comment by michaelbina** [comment]
What is that alternative?

---

Michael Daniel Bina
michaelbina@icloud.com
(310) 990-1102

**Comment by tconroy** [comment]
I ended up going with the [Angular-Famous-Ionic Generator](https://github.com/thaiat/generator-angular-famous-ionic). Don't know if it'll fit your needs but you can check it out.

**Comment by rosstapson** [comment]
double woot!
